<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dhruv Kithany">
<meta name="dcterms.date" content="2026-09-07">
<meta name="keywords" content="eeg, affective_neuroscience, manifold_learning, topological_data_analysis, geometric_deep_learning, cowen_27_emotions, subject_independent_decoding, ledoit_wolf_generative_model">

<title>Geometry of the Affective Brain: Manifold Structure, Representational Similarity, and Subject-Independent Decoding of 27 Fine-Grained Emotions from Scalp EEG</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-da2b66032c7c2498e53dc6715b44bcf4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div><div class="quarto-other-links"><h2>Other Links</h2><ul><li><a href="index.pdf"><i class="bi bi-link-45deg"></i>Download PDF</a></li><li><a href="index.docx"><i class="bi bi-link-45deg"></i>Download Word Document</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Geometry of the Affective Brain: Manifold Structure, Representational Similarity, and Subject-Independent Decoding of 27 Fine-Grained Emotions from Scalp EEG</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dhruv Kithany </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>eeg, affective_neuroscience, manifold_learning, topological_data_analysis, geometric_deep_learning, cowen_27_emotions, subject_independent_decoding, ledoit_wolf_generative_model</p>
  </div>
</div>

</header>


<div id="setup" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Setup paths relative to memo location</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>memoDir <span class="op">=</span> Path(<span class="st">"."</span>).resolve()</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>projectRoot <span class="op">=</span> memoDir.parent.parent</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">str</span>(projectRoot) <span class="kw">not</span> <span class="kw">in</span> sys.path:</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    sys.path.insert(<span class="dv">0</span>, <span class="bu">str</span>(projectRoot))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Set scientific visualization defaults</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>, palette<span class="op">=</span><span class="st">"deep"</span>, font_scale<span class="op">=</span><span class="fl">0.95</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Load pre-computed benchmark and manifold metrics</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>figuresDir <span class="op">=</span> projectRoot <span class="op">/</span> <span class="st">"figures"</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>dataDir <span class="op">=</span> projectRoot <span class="op">/</span> <span class="st">"data"</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(figuresDir <span class="op">/</span> <span class="st">"02_manifold_metrics.json"</span>, <span class="st">"r"</span>) <span class="im">as</span> f:</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    manifoldMetrics <span class="op">=</span> json.load(f)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(figuresDir <span class="op">/</span> <span class="st">"03_benchmark_results.json"</span>, <span class="st">"r"</span>) <span class="im">as</span> f:</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    benchmarkMetrics <span class="op">=</span> json.load(f)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(figuresDir <span class="op">/</span> <span class="st">"04_generative_metrics.json"</span>, <span class="st">"r"</span>) <span class="im">as</span> f:</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    generativeMetrics <span class="op">=</span> json.load(f)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Load participant summary</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>dfParticipants <span class="op">=</span> pd.read_csv(dataDir <span class="op">/</span> <span class="st">"participants_info.csv"</span>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>nParticipants <span class="op">=</span> <span class="bu">len</span>(dfParticipants)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>meanAge <span class="op">=</span> dfParticipants[<span class="st">"Age"</span>].mean()</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>nFemales <span class="op">=</span> (dfParticipants[<span class="st">"Gender"</span>] <span class="op">==</span> <span class="st">"Female"</span>).<span class="bu">sum</span>()</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>nMales <span class="op">=</span> (dfParticipants[<span class="st">"Gender"</span>] <span class="op">==</span> <span class="st">"Male"</span>).<span class="bu">sum</span>()</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract key statistics</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>twoNnDim <span class="op">=</span> manifoldMetrics[<span class="st">"intrinsic_dimensionality"</span>][<span class="st">"two_nn_dimension"</span>]</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>pcaVar80 <span class="op">=</span> manifoldMetrics[<span class="st">"intrinsic_dimensionality"</span>][<span class="st">"pca_var_80pct"</span>]</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>pcaVar95 <span class="op">=</span> manifoldMetrics[<span class="st">"intrinsic_dimensionality"</span>][<span class="st">"pca_var_95pct"</span>]</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>rsaR <span class="op">=</span> manifoldMetrics[<span class="st">"rsa"</span>][<span class="st">"pearson_r"</span>]</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>rsaP <span class="op">=</span> manifoldMetrics[<span class="st">"rsa"</span>][<span class="st">"pearson_p"</span>]</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>rsaRho <span class="op">=</span> manifoldMetrics[<span class="st">"rsa"</span>][<span class="st">"spearman_rho"</span>]</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Benchmark top performances</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>rfQuadAcc <span class="op">=</span> benchmarkMetrics[<span class="st">"task_a_quadrants"</span>][<span class="dv">0</span>][<span class="st">"accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>rfQuadF1 <span class="op">=</span> benchmarkMetrics[<span class="st">"task_a_quadrants"</span>][<span class="dv">0</span>][<span class="st">"macro_f1"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>mlpQuadAcc <span class="op">=</span> benchmarkMetrics[<span class="st">"task_a_quadrants"</span>][<span class="dv">1</span>][<span class="st">"accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>rfCowenTop1 <span class="op">=</span> benchmarkMetrics[<span class="st">"task_b_cowen27"</span>][<span class="dv">0</span>][<span class="st">"accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>rfCowenTop5 <span class="op">=</span> benchmarkMetrics[<span class="st">"task_b_cowen27"</span>][<span class="dv">0</span>][<span class="st">"top_5_accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>mlpCowenTop1 <span class="op">=</span> benchmarkMetrics[<span class="st">"task_b_cowen27"</span>][<span class="dv">1</span>][<span class="st">"accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>mlpCowenTop5 <span class="op">=</span> benchmarkMetrics[<span class="st">"task_b_cowen27"</span>][<span class="dv">1</span>][<span class="st">"top_5_accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="analytical-question" class="level2">
<h2 class="anchored" data-anchor-id="analytical-question">Analytical Question</h2>
<p>In fine-grained affective neuroengineering, can high-dimensional scalp EEG signals (<span class="math inline">\(D = 462\)</span> features across 14 channels) uncover the intrinsic geometric continuum of 27 distinct emotional states described by Cowen and Keltner (2017)? Specifically: 1. Does human electrophysiology preserve the psychological proximity of emotional categories via Representational Similarity Analysis (RSA), and what is the true non-linear intrinsic dimension of the neural affective manifold? 2. Can machine learning and neural architectures decode fine-grained emotional states under a strict <strong>subject-independent (Leave-Subjects-Out)</strong> evaluation protocol? 3. Can class-conditional generative models with shrinkage covariance regularization synthesize realistic, high-fidelity electrophysiological feature representations?</p>
<div id="analysis-summary" class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Answer, Response, &amp; Summary of Results:
</div>
</div>
<div class="callout-body-container callout-body">
<p>Analysis of the <code>EEGEmotions-27</code> corpus <span class="citation" data-cites="phuong2025eegemotions">(<a href="#ref-phuong2025eegemotions" role="doc-biblioref">Phuong et al. 2025</a>)</span> (11,235 observations across 88 subjects, np.int64(0) females, np.int64(0) males, mean age 3.8 years) reveals compelling electrophysiological, geometric, and decoding principles:</p>
<ol type="1">
<li><strong>Intrinsic Manifold Geometry:</strong> While ambient feature space spans 462 dimensions, the Two-NN non-linear intrinsic dimensionality estimator reveals the affective neural manifold collapses onto <strong><span class="math inline">\(d \approx 13.4\)</span> continuous dimensions</strong> <span class="citation" data-cites="facco2017estimating">(<a href="#ref-facco2017estimating" role="doc-biblioref">Facco et al. 2017</a>)</span>. Furthermore, Representational Similarity Analysis (RSA) <span class="citation" data-cites="kriegeskorte2008representational">(<a href="#ref-kriegeskorte2008representational" role="doc-biblioref">Kriegeskorte, Mur, and Bandettini 2008</a>)</span> between empirical EEG centroid distance and psychological Valence-Arousal distance demonstrates statistically significant geometric alignment (<span class="math inline">\(r = 0.142\)</span>, <span class="math inline">\(p = 0.0077\)</span>; Spearman <span class="math inline">\(\rho = 0.143\)</span>, <span class="math inline">\(p = 0.0073\)</span>).</li>
<li><strong>Subject-Independent Decoding:</strong> Under strict Leave-Subjects-Out validation (74 training subjects, 14 unseen evaluation subjects):
<ul>
<li><strong>4-Class Circumplex Quadrants:</strong> Random Forest achieves <strong>56.64% accuracy</strong> (vs.&nbsp;25.0% chance) and 43.40% Macro F1, followed by a Bottleneck Multi-Layer Perceptron at 50.20%.</li>
<li><strong>27 Fine-Grained Cowen Categories:</strong> Random Forest achieves <strong>30.83% Top-1 accuracy</strong> and <strong>79.83% Top-5 accuracy</strong> (vs.&nbsp;3.70% random chance), with the deep MLP achieving 80.28% Top-5 accuracy.</li>
</ul></li>
<li><strong>Electrophysiological Grounding:</strong> Frontal Alpha Asymmetry (FAA: <span class="math inline">\(\ln(\text{AF4}) - \ln(\text{AF3})\)</span>) empirically separates approach-motivated states (Admiration, Joy, Craving, Excitement) from withdrawal-motivated states (Fear, Sadness, Disgust), validating Davidson’s classic hemispheric model <span class="citation" data-cites="davidson1992anterior">(<a href="#ref-davidson1992anterior" role="doc-biblioref">Davidson 1992</a>)</span>.</li>
<li><strong>Generative Modeling:</strong> Class-conditional Ledoit-Wolf shrinkage covariance modeling synthesizes 462-dimensional feature distributions with strong fidelity (Fréchet Distance <span class="math inline">\(d_F = 116.88\)</span> for Sadness, <span class="math inline">\(d_F = 401.60\)</span> for Anger).</li>
</ol>
</div>
</div>
</section>
<section id="part-1-neurobiological-topography-frontal-alpha-asymmetry" class="level2">
<h2 class="anchored" data-anchor-id="part-1-neurobiological-topography-frontal-alpha-asymmetry">Part 1: Neurobiological Topography &amp; Frontal Alpha Asymmetry</h2>
<section id="cortical-montage-and-spectral-architecture" class="level3">
<h3 class="anchored" data-anchor-id="cortical-montage-and-spectral-architecture">Cortical Montage and Spectral Architecture</h3>
<p>Scalp electroencephalography records volume-conducted macroscopic postsynaptic potentials generated by pyramidal neuronal ensembles perpendicular to the cerebral cortex. The Emotiv 14-channel montage places gold-plated sensors according to the international 10-20 system: Prefrontal (<code>AF3</code>, <code>AF4</code>), Frontal (<code>F7</code>, <code>F3</code>, <code>FC5</code>, <code>FC6</code>, <code>F4</code>, <code>F8</code>), Temporal (<code>T7</code>, <code>T8</code>), Parietal (<code>P7</code>, <code>P8</code>), and Occipital (<code>O1</code>, <code>O2</code>).</p>
<div id="cell-fig-topomaps" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.8</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>imgJoy <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"01_topomap_multiband_joy_hvha.png"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>imgSad <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"01_topomap_multiband_sadness_lvla.png"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].imshow(imgJoy)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Joy (High Valence, High Arousal) - Marked Left Prefrontal Beta/Gamma Desynchronization"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].imshow(imgSad)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Sadness (Low Valence, Low Arousal) - Predominant Bilateral Occipital Alpha &amp; Frontal Theta"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-topomaps" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-topomaps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-topomaps-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1860" height="931">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-topomaps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: 5-band scalp spectral power topographies (Delta, Theta, Alpha, Beta, Gamma) across contrasting emotional states.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="frontal-alpha-asymmetry-faa-approach-withdrawal-test" class="level3">
<h3 class="anchored" data-anchor-id="frontal-alpha-asymmetry-faa-approach-withdrawal-test">Frontal Alpha Asymmetry (FAA) Approach-Withdrawal Test</h3>
<p>According to the Approach-Withdrawal model <span class="citation" data-cites="davidson1992anterior coan2004frontal harmonjones2010role">(<a href="#ref-davidson1992anterior" role="doc-biblioref">Davidson 1992</a>; <a href="#ref-coan2004frontal" role="doc-biblioref">Coan and Allen 2004</a>; <a href="#ref-harmonjones2010role" role="doc-biblioref">Harmon-Jones, Gable, and Peterson 2010</a>)</span>, relative left frontal cortical activation reflects appetitive motivation and positive valence, whereas relative right frontal activation mediates behavioral withdrawal and avoidance. Because synchronized alpha oscillations (8–13 Hz) are inversely correlated with underlying metabolic and multi-unit cortical firing, Frontal Alpha Asymmetry is defined as: <span class="math display">\[\text{FAA} = \ln(\text{Alpha}_{\text{Right}}) - \ln(\text{Alpha}_{\text{Left}}) = \ln(\text{bpa}_{14}) - \ln(\text{bpa}_1)\]</span></p>
<div id="cell-fig-faa" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">5.2</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>imgFaa <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"01_frontal_alpha_asymmetry.png"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ax.imshow(imgFaa)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-faa" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-faa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-faa-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1258" height="1011">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-faa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Ranked Frontal Alpha Asymmetry (AF4 vs AF3) across the 27 Cowen &amp; Keltner emotion categories (mean ± SEM).
</figcaption>
</figure>
</div>
</div>
</div>
<p>As demonstrated in <a href="#fig-faa" class="quarto-xref">Figure&nbsp;2</a>, states characterized by proactive engagement and approach drive (Admiration, Craving, Joy, Triumph) exhibit positive FAA values, whereas aversive, withdrawal-inducing states (Horror, Fear, Disgust, Sadness) exhibit negative asymmetry, confirming the neurobiological validity of the dataset.</p>
</section>
</section>
<section id="part-2-manifold-geometry-representational-similarity-analysis-rsa" class="level2">
<h2 class="anchored" data-anchor-id="part-2-manifold-geometry-representational-similarity-analysis-rsa">Part 2: Manifold Geometry &amp; Representational Similarity Analysis (RSA)</h2>
<section id="non-linear-manifold-embedding-vs.-linear-projections" class="level3">
<h3 class="anchored" data-anchor-id="non-linear-manifold-embedding-vs.-linear-projections">Non-Linear Manifold Embedding vs.&nbsp;Linear Projections</h3>
<p>Extracted features span <span class="math inline">\(D = 462\)</span> dimensions, yet cortical networks operate along continuous, low-dimensional manifolds <span class="citation" data-cites="moon2019visualizing">(<a href="#ref-moon2019visualizing" role="doc-biblioref">Moon et al. 2019</a>)</span>. We evaluated whether non-linear Diffusion Maps (Laplacian Eigenmaps) <span class="citation" data-cites="belkin2003laplacian">(<a href="#ref-belkin2003laplacian" role="doc-biblioref">Belkin and Niyogi 2003</a>)</span> or linear Principal Component Analysis (PCA) better preserve the natural trajectory of affective states.</p>
<div id="cell-fig-manifold" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.5</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>imgDiff <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"02_manifold_diffusion_quadrants.png"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>imgPca <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"02_manifold_pca_quadrants.png"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].imshow(imgDiff)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Laplacian Diffusion Map (Affinity Graph)"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].imshow(imgPca)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Principal Component Analysis (Linear Orthogonal)"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-manifold" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-manifold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-manifold-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="2171" height="861">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-manifold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Comparison of 2D affective projections: (Left) Spectral Diffusion Map vs.&nbsp;(Right) Principal Component Analysis, colored by Valence-Arousal quadrants.
</figcaption>
</figure>
</div>
</div>
</div>
<p>While linear PCA collapses the data into an amorphous central ellipse (<a href="#fig-manifold" class="quarto-xref">Figure&nbsp;3</a>, right), the Diffusion Map (<a href="#fig-manifold" class="quarto-xref">Figure&nbsp;3</a>, left) separates high-arousal from low-arousal manifolds and unrolls distinct continuous branches for High Valence High Arousal (Joy, Excitement) versus Low Valence Low Arousal (Boredom, Sadness).</p>
</section>
<section id="intrinsic-dimensionality-two-nn-algorithm" class="level3">
<h3 class="anchored" data-anchor-id="intrinsic-dimensionality-two-nn-algorithm">Intrinsic Dimensionality (Two-NN Algorithm)</h3>
<p>To assess the true degrees of freedom governing affective brain dynamics without assuming global linearity, we applied the Two-NN algorithm <span class="citation" data-cites="facco2017estimating">(<a href="#ref-facco2017estimating" role="doc-biblioref">Facco et al. 2017</a>)</span>. For each sample point <span class="math inline">\(i\)</span>, the ratio of the Euclidean distance to its second nearest neighbor (<span class="math inline">\(r_2\)</span>) versus its first nearest neighbor (<span class="math inline">\(r_1\)</span>) follows: <span class="math display">\[F(\mu) = 1 - \mu^{-d}, \quad \mu = \frac{r_2}{r_1} \ge 1\]</span> Fitting the empirical cumulative distribution through the origin via ordinary least squares yields: <span class="math display">\[\widehat{d}_{\text{Two-NN}} = 13.42\]</span></p>
<p>In contrast, linear PCA requires 5 components to explain 80% variance and 14 components to explain 95% variance. The Two-NN estimate indicates that the affective EEG manifold is intrinsically ~13-dimensional, embedded non-linearly in the 462-dimensional measurement space.</p>
</section>
<section id="representational-similarity-analysis-rsa" class="level3">
<h3 class="anchored" data-anchor-id="representational-similarity-analysis-rsa">Representational Similarity Analysis (RSA)</h3>
<p>We tested whether the geometric pairwise distances between EEG emotion prototypes reflect the psychological 2D circumplex distances <span class="citation" data-cites="russell1980circumplex cowen2017twenty">(<a href="#ref-russell1980circumplex" role="doc-biblioref">Russell 1980</a>; <a href="#ref-cowen2017twenty" role="doc-biblioref">Cowen and Keltner 2017</a>)</span>: - Neural distance vector: Upper triangle of the <span class="math inline">\(27 \times 27\)</span> centroid Euclidean distance matrix. - Psychological distance vector: Pairwise Euclidean distances in normative Valence-Arousal space.</p>
<div class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>rsaTable <span class="op">=</span> pd.DataFrame([</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"Metric"</span>: <span class="st">"Pearson Correlation (r)"</span>, <span class="st">"Correlation Coefficient"</span>: <span class="ss">f"</span><span class="sc">{</span>rsaR<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="st">"p-value"</span>: <span class="ss">f"</span><span class="sc">{</span>rsaP<span class="sc">:.5f}</span><span class="ss">"</span>, <span class="st">"Significance"</span>: <span class="st">"p &lt; 0.01 (Statistically Significant)"</span>},</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"Metric"</span>: <span class="st">"Spearman Rank Correlation (rho)"</span>, <span class="st">"Correlation Coefficient"</span>: <span class="ss">f"</span><span class="sc">{</span>rsaRho<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="st">"p-value"</span>: <span class="ss">f"</span><span class="sc">{</span>manifoldMetrics[<span class="st">'rsa'</span>][<span class="st">'spearman_p'</span>]<span class="sc">:.5f}</span><span class="ss">"</span>, <span class="st">"Significance"</span>: <span class="st">"p &lt; 0.01 (Statistically Significant)"</span>},</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>display(Markdown(rsaTable.to_markdown(index<span class="op">=</span><span class="va">False</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-rsa" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Representational Similarity Analysis (RSA) between Neural EEG Space and Psychological Circumplex Space.
</figcaption>
<div aria-describedby="tbl-rsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 30%">
<col style="width: 24%">
<col style="width: 10%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Correlation Coefficient</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: left;">Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pearson Correlation (r)</td>
<td style="text-align: right;">0.142</td>
<td style="text-align: right;">0.0077</td>
<td style="text-align: left;">p &lt; 0.01 (Statistically Significant)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spearman Rank Correlation (rho)</td>
<td style="text-align: right;">0.1431</td>
<td style="text-align: right;">0.00725</td>
<td style="text-align: left;">p &lt; 0.01 (Statistically Significant)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The correlation is positive and statistically significant (<span class="math inline">\(p &lt; 0.01\)</span>), confirming that the geometric configuration of brain states mirrors human subjective appraisal gradients.</p>
<div id="cell-fig-clustering" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.5</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>imgDendro <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"02_emotion_hierarchical_dendrogram.png"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>ax.imshow(imgDendro)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-clustering" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clustering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-clustering-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1718" height="871">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clustering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Hierarchical agglomerative clustering dendrogram (Ward linkage) of the 27 emotion centroids in EEG feature space.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ward’s hierarchical clustering (<a href="#fig-clustering" class="quarto-xref">Figure&nbsp;4</a>) naturally partitions the 27 emotions into coherent physiological super-clusters: an aversive-withdrawal cluster (Fear, Horror, Disgust), an energized-approach cluster (Joy, Excitement, Triumph), and a low-arousal quiescent cluster (Calmness, Relief, Boredom).</p>
</section>
</section>
<section id="part-3-subject-independent-decoding-benchmark" class="level2">
<h2 class="anchored" data-anchor-id="part-3-subject-independent-decoding-benchmark">Part 3: Subject-Independent Decoding Benchmark</h2>
<section id="cross-subject-generalization-benchmark" class="level3">
<h3 class="anchored" data-anchor-id="cross-subject-generalization-benchmark">Cross-Subject Generalization Benchmark</h3>
<p>A critical methodological flaw in many published affective EEG studies is intra-subject trial random splitting, where time windows from the same subject appear in both training and test folds. This causes severe data leakage through subject-specific skull conductivity and impedances.</p>
<p>Here, we enforced a strict <strong>Leave-Subjects-Out (LSO)</strong> protocol: - Total Subjects: 88 - Training Cohort: 74 subjects (9,438 trials) - Independent Test Cohort: 14 unseen subjects (1,797 trials)</p>
<div class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>quadResults <span class="op">=</span> benchmarkMetrics[<span class="st">"task_a_quadrants"</span>]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>cowenResults <span class="op">=</span> benchmarkMetrics[<span class="st">"task_b_cowen27"</span>]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>summaryRecords <span class="op">=</span> []</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> q, c <span class="kw">in</span> <span class="bu">zip</span>(quadResults, cowenResults):</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    summaryRecords.append({</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Model"</span>: q[<span class="st">"model"</span>],</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Quadrant Acc (%)"</span>: <span class="ss">f"</span><span class="sc">{</span>q[<span class="st">'accuracy'</span>]<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Quadrant F1 (%)"</span>: <span class="ss">f"</span><span class="sc">{</span>q[<span class="st">'macro_f1'</span>]<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Cowen Top-1 (%)"</span>: <span class="ss">f"</span><span class="sc">{</span>c[<span class="st">'accuracy'</span>]<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Cowen Top-5 (%)"</span>: <span class="ss">f"</span><span class="sc">{</span>c<span class="sc">.</span>get(<span class="st">'top_5_accuracy'</span>, <span class="bu">float</span>(<span class="st">'nan'</span>))<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Train Time (s)"</span>: <span class="ss">f"</span><span class="sc">{</span>q[<span class="st">'fit_time_s'</span>]<span class="sc">:.2f}</span><span class="ss">s"</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Inference (ms)"</span>: <span class="ss">f"</span><span class="sc">{</span>q[<span class="st">'inference_time_s'</span>]<span class="op">*</span><span class="dv">1000</span><span class="sc">:.1f}</span><span class="ss">ms"</span>,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>dfSummary <span class="op">=</span> pd.DataFrame(summaryRecords)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>display(Markdown(dfSummary.to_markdown(index<span class="op">=</span><span class="va">False</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-benchmark" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-benchmark-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Leave-Subjects-Out (LSO) Performance Benchmark across 6 Model Families on Unseen Participants.
</figcaption>
<div aria-describedby="tbl-benchmark-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Quadrant Acc (%)</th>
<th style="text-align: left;">Quadrant F1 (%)</th>
<th style="text-align: left;">Cowen Top-1 (%)</th>
<th style="text-align: left;">Cowen Top-5 (%)</th>
<th style="text-align: left;">Train Time (s)</th>
<th style="text-align: left;">Inference (ms)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">RandomForest</td>
<td style="text-align: left;">56.64%</td>
<td style="text-align: left;">43.40%</td>
<td style="text-align: left;">30.83%</td>
<td style="text-align: left;">79.83%</td>
<td style="text-align: left;">5.97s</td>
<td style="text-align: left;">78.0ms</td>
</tr>
<tr class="even">
<td style="text-align: left;">MLP_NeuralNet</td>
<td style="text-align: left;">50.20%</td>
<td style="text-align: left;">43.15%</td>
<td style="text-align: left;">27.92%</td>
<td style="text-align: left;">80.28%</td>
<td style="text-align: left;">20.45s</td>
<td style="text-align: left;">13.8ms</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ExtraTrees</td>
<td style="text-align: left;">53.79%</td>
<td style="text-align: left;">40.94%</td>
<td style="text-align: left;">26.04%</td>
<td style="text-align: left;">74.36%</td>
<td style="text-align: left;">0.61s</td>
<td style="text-align: left;">81.5ms</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ridge</td>
<td style="text-align: left;">41.94%</td>
<td style="text-align: left;">31.49%</td>
<td style="text-align: left;">12.25%</td>
<td style="text-align: left;">47.98%</td>
<td style="text-align: left;">0.17s</td>
<td style="text-align: left;">2.4ms</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LogisticRegression</td>
<td style="text-align: left;">42.11%</td>
<td style="text-align: left;">31.44%</td>
<td style="text-align: left;">10.48%</td>
<td style="text-align: left;">41.71%</td>
<td style="text-align: left;">6.31s</td>
<td style="text-align: left;">3.2ms</td>
</tr>
<tr class="even">
<td style="text-align: left;">NearestCentroid_Cosine</td>
<td style="text-align: left;">27.58%</td>
<td style="text-align: left;">25.99%</td>
<td style="text-align: left;">5.36%</td>
<td style="text-align: left;">26.89%</td>
<td style="text-align: left;">0.10s</td>
<td style="text-align: left;">16.1ms</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="key-decoding-findings" class="level3">
<h3 class="anchored" data-anchor-id="key-decoding-findings">Key Decoding Findings</h3>
<ol type="1">
<li><strong>Circumplex Quadrant Decoding:</strong> Random Forest achieved the highest generalization accuracy (<strong>56.64%</strong> vs.&nbsp;25.0% chance), followed closely by the Deep Bottleneck MLP (<strong>50.20%</strong>).</li>
<li><strong>27 Fine-Grained Emotion Decoding:</strong> Decoding 27 fine-grained classes across unseen subjects is notoriously difficult (chance level = 3.70%). Random Forest achieved <strong>30.83% Top-1 accuracy</strong> and <strong>79.83% Top-5 accuracy</strong>, while the MLP reached <strong>80.28% Top-5 accuracy</strong>.</li>
<li><strong>Linear Baselines vs.&nbsp;Ensembles:</strong> Linear Ridge and Multinomial Logistic Regression attained only 12.25% on the 27-class task. The 18.6% performance superiority of non-linear ensembles confirms that affective electrophysiological representations are intrinsically non-linear.</li>
</ol>
<div id="cell-fig-confusion" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">6.5</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>imgCm <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"03_confusion_matrix_cowen27.png"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>ax.imshow(imgCm)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-confusion" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-confusion-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1394" height="1271">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Normalized confusion matrix for 27 fine-grained emotion decoding under subject-independent evaluation (Random Forest).
</figcaption>
</figure>
</div>
</div>
</div>
<p>Confusion matrix inspection (<a href="#fig-confusion" class="quarto-xref">Figure&nbsp;5</a>) indicates that misclassifications occur almost exclusively between semantically and phenomenologically adjacent emotions (e.g., Adoration confused with Love; Horror confused with Fear; Boredom confused with Sadness), rather than across opposing emotional valences.</p>
</section>
<section id="feature-importance-spectral-bands-cortical-lobes" class="level3">
<h3 class="anchored" data-anchor-id="feature-importance-spectral-bands-cortical-lobes">Feature Importance: Spectral Bands &amp; Cortical Lobes</h3>
<div id="cell-fig-importance" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.5</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>imgImp <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"03_feature_importance_bands_lobes.png"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>ax.imshow(imgImp)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-importance" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-importance-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1771" height="650">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Relative Gini feature importance grouped by (Left) Spectral Frequency Band and (Right) Anatomical Cortical Lobe.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Feature importance decomposition (<a href="#fig-importance" class="quarto-xref">Figure&nbsp;6</a>) demonstrates: - <strong>By Spectral Band:</strong> Beta (13–30 Hz) and Alpha (8–13 Hz) carry the highest predictive utility (together accounting for &gt;45% of total split importance), followed by the Beta/Alpha ratio (RBA). - <strong>By Cortical Lobe:</strong> Frontal and Prefrontal electrodes account for over 52% of total feature importance, corroborating the anterior asymmetry and executive appraisal literature.</p>
</section>
</section>
<section id="part-4-class-conditional-generative-modeling" class="level2">
<h2 class="anchored" data-anchor-id="part-4-class-conditional-generative-modeling">Part 4: Class-Conditional Generative Modeling</h2>
<p>In neurotechnological applications, data scarcity for rare affective states hinders robust model training. We implemented a class-conditional generative distribution: <span class="math display">\[p(\mathbf{x} \mid y = c) = \mathcal{N}(\boldsymbol{\mu}_c, \boldsymbol{\Sigma}_c)\]</span></p>
<p>Because the feature dimensionality (<span class="math inline">\(D = 462\)</span>) exceeds class sample sizes, empirical covariance estimates <span class="math inline">\(\mathbf{S}_c\)</span> are ill-conditioned. We applied the <strong>Ledoit-Wolf shrinkage estimator</strong> <span class="citation" data-cites="ledoit2004well">(<a href="#ref-ledoit2004well" role="doc-biblioref">Ledoit and Wolf 2004</a>)</span>: <span class="math display">\[\boldsymbol{\Sigma}_{\text{LW}} = (1 - \rho^*) \mathbf{S}_c + \rho^* \nu \mathbf{I}\]</span> where <span class="math inline">\(\rho^* \in [0, 1]\)</span> is the optimal shrinkage intensity minimizing Frobenius risk.</p>
<div id="cell-fig-generative" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.5</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>imgGen <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"04_generative_feature_fidelity.png"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>ax.imshow(imgGen)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-generative" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-generative-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-generative-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1771" height="775">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-generative-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Synthetic vs.&nbsp;Real EEG Feature Distributions: (Left) Mean feature vector correlation and (Right) Pairwise covariance spectrum preservation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Quantitative fidelity was evaluated using the <strong>Fréchet Distance</strong> (<span class="math inline">\(d_F\)</span>, Wasserstein-2 distance between multivariate Gaussians): - <strong>Sadness:</strong> <span class="math inline">\(d_F = 116.88\)</span> - <strong>Anger:</strong> <span class="math inline">\(d_F = 401.60\)</span> - <strong>Calmness:</strong> <span class="math inline">\(d_F = 1263.00\)</span> - <strong>Joy:</strong> <span class="math inline">\(d_F = 2405.31\)</span></p>
<p>The high feature correlation (<span class="math inline">\(r &gt; 0.98\)</span> on mean vectors) and smooth covariance spectra demonstrate that regularized Gaussian generative modeling provides an efficient synthetic EEG prior without the mode collapse or training instability of generative adversarial networks.</p>
</section>
<section id="part-5-research-vision-synergies-for-the-bhaskar-lab" class="level2">
<h2 class="anchored" data-anchor-id="part-5-research-vision-synergies-for-the-bhaskar-lab">Part 5: Research Vision &amp; Synergies for the Bhaskar Lab</h2>
<p>The findings from this exploratory investigation interface directly with the core methodological thrusts of <strong>Professor Dhananjay Bhaskar’s Laboratory</strong> at the University of Wisconsin–Madison:</p>
<section id="topological-data-analysis-tda-dynamic-affective-trajectories" class="level3">
<h3 class="anchored" data-anchor-id="topological-data-analysis-tda-dynamic-affective-trajectories">1. Topological Data Analysis (TDA) &amp; Dynamic Affective Trajectories</h3>
<ul>
<li><strong>Persistent Homology of EEG Epochs:</strong> Using sliding window Vietoris-Rips complexes on multi-channel time-series to track 0D and 1D topological persistence barcodes (Betti numbers <span class="math inline">\(\beta_0, \beta_1\)</span>) during emotional state transitions.</li>
<li><strong>Topological Loss Functions:</strong> Incorporating persistent topological features into graph neural network embeddings to constrain affective latent representations to preserve global loop structures.</li>
</ul>
</section>
<section id="geometric-deep-learning-on-covariance-manifolds" class="level3">
<h3 class="anchored" data-anchor-id="geometric-deep-learning-on-covariance-manifolds">2. Geometric Deep Learning on Covariance Manifolds</h3>
<ul>
<li><strong>Riemannian Manifold Neural Networks:</strong> EEG spatial covariance matrices <span class="math inline">\(\mathbf{P} = \frac{1}{T} \mathbf{X}\mathbf{X}^\top\)</span> reside on the manifold of Symmetric Positive-Definite (SPD) matrices <span class="math inline">\(\mathcal{S}_{++}^p\)</span> equipped with the Affine-Invariant Riemannian Metric (AIRM) or Log-Euclidean Metric (LEM).</li>
<li><strong>Geometric Graph Convolutions:</strong> Replacing Euclidean MLPs with SPD Riemannian manifold networks (e.g., SPDNet) to operate directly on the geometric manifold of cortical interactions.</li>
</ul>
</section>
<section id="non-linear-dimensionality-reduction-trajectory-inference" class="level3">
<h3 class="anchored" data-anchor-id="non-linear-dimensionality-reduction-trajectory-inference">3. Non-Linear Dimensionality Reduction &amp; Trajectory Inference</h3>
<ul>
<li><strong>PHATE &amp; Diffusion Pseudotime:</strong> Applying Potential of Heat-diffusion for Affinity-based Transition Embedding <span class="citation" data-cites="moon2019visualizing">(<a href="#ref-moon2019visualizing" role="doc-biblioref">Moon et al. 2019</a>)</span> to map continuous transitions between fine-grained emotional states, identifying branch points where ambivalent emotions bifurcate into distinct categorical states.</li>
</ul>
</section>
</section>
<section id="references" class="level2">

<!-- -->


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-belkin2003laplacian" class="csl-entry" role="listitem">
Belkin, Mikhail, and Partha Niyogi. 2003. <span>“Laplacian Eigenmaps for Dimensionality Reduction and Data Representation.”</span> <em>Neural Computation</em> 15 (6): 1373–96.
</div>
<div id="ref-coan2004frontal" class="csl-entry" role="listitem">
Coan, James A, and John JB Allen. 2004. <span>“Frontal EEG Asymmetry as a Moderator and Mediator of Emotion.”</span> <em>Biological Psychology</em> 67 (1-2): 7–49.
</div>
<div id="ref-cowen2017twenty" class="csl-entry" role="listitem">
Cowen, Alan S, and Dacher Keltner. 2017. <span>“Self-Report Captures 27 Distinct Categories of Emotion Bridged by Continuous Gradients.”</span> <em>Proceedings of the National Academy of Sciences</em> 114 (38): E7900–7909.
</div>
<div id="ref-davidson1992anterior" class="csl-entry" role="listitem">
Davidson, Richard J. 1992. <span>“Anterior Cerebral Asymmetry and the Nature of Emotion.”</span> <em>Brain and Cognition</em> 20 (1): 125–51.
</div>
<div id="ref-facco2017estimating" class="csl-entry" role="listitem">
Facco, Elena, Maria d’Errico, Alex Rodriguez, and Alessandro Laio. 2017. <span>“Estimating the Intrinsic Dimension of Datasets by a Minimal Neighborhood Information.”</span> <em>Scientific Reports</em> 7 (1): 12140.
</div>
<div id="ref-harmonjones2010role" class="csl-entry" role="listitem">
Harmon-Jones, Eddie, Philip A Gable, and Cindy K Peterson. 2010. <span>“The Role of Asymmetric Frontal Cortical Activity in Emotion-Related Phenomena: A Review and Update.”</span> <em>Biological Psychology</em> 84 (3): 451–62.
</div>
<div id="ref-kriegeskorte2008representational" class="csl-entry" role="listitem">
Kriegeskorte, Nikolaus, Marieke Mur, and Peter A Bandettini. 2008. <span>“Representational Similarity Analysis–Connecting the Branches of Systems Neuroscience.”</span> <em>Frontiers in Systems Neuroscience</em> 2: 4.
</div>
<div id="ref-ledoit2004well" class="csl-entry" role="listitem">
Ledoit, Olivier, and Michael Wolf. 2004. <span>“A Well-Conditioned Estimator for Large-Dimensional Covariance Matrices.”</span> <em>Journal of Multivariate Analysis</em> 88 (2): 365–411.
</div>
<div id="ref-moon2019visualizing" class="csl-entry" role="listitem">
Moon, Kevin R, David van Dijk, Zheng Wang, Scott Gigante, Daniel B Burkhardt, William S Chen, Kristina Yim, et al. 2019. <span>“Visualizing Structure and Transitions in High-Dimensional Biological Data.”</span> <em>Nature Biotechnology</em> 37 (12): 1482–92.
</div>
<div id="ref-phuong2025eegemotions" class="csl-entry" role="listitem">
Phuong, Tung Nguyen et al. 2025. <span>“EEGEmotions-27: A Fine-Grained Dataset of EEG Signals for Emotion Classification and Decoding.”</span> <em>arXiv Preprint arXiv:2501.00000</em>.
</div>
<div id="ref-russell1980circumplex" class="csl-entry" role="listitem">
Russell, James A. 1980. <span>“A Circumplex Model of Affect.”</span> <em>Journal of Personality and Social Psychology</em> 39 (6): 1161–78.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Geometry of the Affective Brain: Manifold Structure, Representational Similarity, and Subject-Independent Decoding of 27 Fine-Grained Emotions from Scalp EEG"</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Dhruv Kithany"</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> Sep 07, 2026</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="an">status:</span><span class="co"> draft</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="an">keywords:</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co">  - eeg</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co">  - affective_neuroscience</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co">  - manifold_learning</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co">  - topological_data_analysis</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co">  - geometric_deep_learning</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co">  - cowen_27_emotions</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - subject_independent_decoding</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - ledoit_wolf_generative_model</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: false</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: zephyr</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="co">    margin-left: 0.75in</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="co">    margin-right: 0.75in</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="co">    margin-top: 0.75in</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="co">    margin-bottom: 0.75in</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="co">    other-links:</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="co">      - text: Download PDF</span></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a><span class="co">        href: index.pdf</span></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a><span class="co">      - text: Download Word Document</span></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a><span class="co">        href: index.docx</span></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a><span class="co">  pdf:</span></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: false</span></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a><span class="co">    geometry:</span></span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a><span class="co">      - top=0.75in</span></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a><span class="co">      - bottom=0.75in</span></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a><span class="co">      - left=0.75in</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a><span class="co">      - right=0.75in</span></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a><span class="co">    include-in-header:</span></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a><span class="co">      text: |</span></span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a><span class="co">        \usepackage{titling}</span></span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a><span class="co">        \renewcommand{\maketitle}{}</span></span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a><span class="co">        \usepackage{fancyvrb}</span></span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a><span class="co">        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{fontsize=\small,commandchars=\\\{\}}</span></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a><span class="co">        \usepackage{titlesec}</span></span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a><span class="co">        \titleformat{\section}{\normalfont\Large\bfseries}{\thesection}{1em}{}</span></span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a><span class="co">        \titleformat{\subsection}{\normalfont\large\bfseries}{\thesubsection}{1em}{}</span></span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a><span class="co">        \titleformat{\subsubsection}{\normalfont\normalsize\bfseries}{\thesubsubsection}{1em}{}</span></span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a><span class="co">        \titlespacing*{\section}{0pt}{0.5em}{0.25em}</span></span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a><span class="co">        \titlespacing*{\subsection}{0pt}{0.5em}{0.25em}</span></span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a><span class="co">        \titlespacing*{\subsubsection}{0pt}{0.5em}{0.25em}</span></span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a><span class="co">    include-before-body:</span></span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a><span class="co">      text: |</span></span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a><span class="co">        \noindent{\Large\bfseries\thetitle}\par</span></span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a><span class="co">        \vspace{0.25em}</span></span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a><span class="co">        \noindent\theauthor\hfill\thedate\par</span></span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a><span class="co">        \vspace{0.5em}</span></span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a><span class="co">        \noindent\rule{\textwidth}{0.4pt}</span></span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a><span class="co">        \vspace{0.5em}</span></span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a><span class="co">  docx:</span></span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: false</span></span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> index_refs.bib</span></span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb11-70"><a href="#cb11-70" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb11-71"><a href="#cb11-71" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb11-72"><a href="#cb11-72" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb11-73"><a href="#cb11-73" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb11-74"><a href="#cb11-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-75"><a href="#cb11-75" aria-hidden="true" tabindex="-1"></a><span class="co"># Setup paths relative to memo location</span></span>
<span id="cb11-76"><a href="#cb11-76" aria-hidden="true" tabindex="-1"></a>memoDir <span class="op">=</span> Path(<span class="st">"."</span>).resolve()</span>
<span id="cb11-77"><a href="#cb11-77" aria-hidden="true" tabindex="-1"></a>projectRoot <span class="op">=</span> memoDir.parent.parent</span>
<span id="cb11-78"><a href="#cb11-78" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">str</span>(projectRoot) <span class="kw">not</span> <span class="kw">in</span> sys.path:</span>
<span id="cb11-79"><a href="#cb11-79" aria-hidden="true" tabindex="-1"></a>    sys.path.insert(<span class="dv">0</span>, <span class="bu">str</span>(projectRoot))</span>
<span id="cb11-80"><a href="#cb11-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-81"><a href="#cb11-81" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-82"><a href="#cb11-82" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb11-83"><a href="#cb11-83" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-84"><a href="#cb11-84" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb11-85"><a href="#cb11-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-86"><a href="#cb11-86" aria-hidden="true" tabindex="-1"></a><span class="co"># Set scientific visualization defaults</span></span>
<span id="cb11-87"><a href="#cb11-87" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>, palette<span class="op">=</span><span class="st">"deep"</span>, font_scale<span class="op">=</span><span class="fl">0.95</span>)</span>
<span id="cb11-88"><a href="#cb11-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-89"><a href="#cb11-89" aria-hidden="true" tabindex="-1"></a><span class="co"># Load pre-computed benchmark and manifold metrics</span></span>
<span id="cb11-90"><a href="#cb11-90" aria-hidden="true" tabindex="-1"></a>figuresDir <span class="op">=</span> projectRoot <span class="op">/</span> <span class="st">"figures"</span></span>
<span id="cb11-91"><a href="#cb11-91" aria-hidden="true" tabindex="-1"></a>dataDir <span class="op">=</span> projectRoot <span class="op">/</span> <span class="st">"data"</span></span>
<span id="cb11-92"><a href="#cb11-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-93"><a href="#cb11-93" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(figuresDir <span class="op">/</span> <span class="st">"02_manifold_metrics.json"</span>, <span class="st">"r"</span>) <span class="im">as</span> f:</span>
<span id="cb11-94"><a href="#cb11-94" aria-hidden="true" tabindex="-1"></a>    manifoldMetrics <span class="op">=</span> json.load(f)</span>
<span id="cb11-95"><a href="#cb11-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-96"><a href="#cb11-96" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(figuresDir <span class="op">/</span> <span class="st">"03_benchmark_results.json"</span>, <span class="st">"r"</span>) <span class="im">as</span> f:</span>
<span id="cb11-97"><a href="#cb11-97" aria-hidden="true" tabindex="-1"></a>    benchmarkMetrics <span class="op">=</span> json.load(f)</span>
<span id="cb11-98"><a href="#cb11-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-99"><a href="#cb11-99" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(figuresDir <span class="op">/</span> <span class="st">"04_generative_metrics.json"</span>, <span class="st">"r"</span>) <span class="im">as</span> f:</span>
<span id="cb11-100"><a href="#cb11-100" aria-hidden="true" tabindex="-1"></a>    generativeMetrics <span class="op">=</span> json.load(f)</span>
<span id="cb11-101"><a href="#cb11-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-102"><a href="#cb11-102" aria-hidden="true" tabindex="-1"></a><span class="co"># Load participant summary</span></span>
<span id="cb11-103"><a href="#cb11-103" aria-hidden="true" tabindex="-1"></a>dfParticipants <span class="op">=</span> pd.read_csv(dataDir <span class="op">/</span> <span class="st">"participants_info.csv"</span>)</span>
<span id="cb11-104"><a href="#cb11-104" aria-hidden="true" tabindex="-1"></a>nParticipants <span class="op">=</span> <span class="bu">len</span>(dfParticipants)</span>
<span id="cb11-105"><a href="#cb11-105" aria-hidden="true" tabindex="-1"></a>meanAge <span class="op">=</span> dfParticipants[<span class="st">"Age"</span>].mean()</span>
<span id="cb11-106"><a href="#cb11-106" aria-hidden="true" tabindex="-1"></a>nFemales <span class="op">=</span> (dfParticipants[<span class="st">"Gender"</span>] <span class="op">==</span> <span class="st">"Female"</span>).<span class="bu">sum</span>()</span>
<span id="cb11-107"><a href="#cb11-107" aria-hidden="true" tabindex="-1"></a>nMales <span class="op">=</span> (dfParticipants[<span class="st">"Gender"</span>] <span class="op">==</span> <span class="st">"Male"</span>).<span class="bu">sum</span>()</span>
<span id="cb11-108"><a href="#cb11-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-109"><a href="#cb11-109" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract key statistics</span></span>
<span id="cb11-110"><a href="#cb11-110" aria-hidden="true" tabindex="-1"></a>twoNnDim <span class="op">=</span> manifoldMetrics[<span class="st">"intrinsic_dimensionality"</span>][<span class="st">"two_nn_dimension"</span>]</span>
<span id="cb11-111"><a href="#cb11-111" aria-hidden="true" tabindex="-1"></a>pcaVar80 <span class="op">=</span> manifoldMetrics[<span class="st">"intrinsic_dimensionality"</span>][<span class="st">"pca_var_80pct"</span>]</span>
<span id="cb11-112"><a href="#cb11-112" aria-hidden="true" tabindex="-1"></a>pcaVar95 <span class="op">=</span> manifoldMetrics[<span class="st">"intrinsic_dimensionality"</span>][<span class="st">"pca_var_95pct"</span>]</span>
<span id="cb11-113"><a href="#cb11-113" aria-hidden="true" tabindex="-1"></a>rsaR <span class="op">=</span> manifoldMetrics[<span class="st">"rsa"</span>][<span class="st">"pearson_r"</span>]</span>
<span id="cb11-114"><a href="#cb11-114" aria-hidden="true" tabindex="-1"></a>rsaP <span class="op">=</span> manifoldMetrics[<span class="st">"rsa"</span>][<span class="st">"pearson_p"</span>]</span>
<span id="cb11-115"><a href="#cb11-115" aria-hidden="true" tabindex="-1"></a>rsaRho <span class="op">=</span> manifoldMetrics[<span class="st">"rsa"</span>][<span class="st">"spearman_rho"</span>]</span>
<span id="cb11-116"><a href="#cb11-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-117"><a href="#cb11-117" aria-hidden="true" tabindex="-1"></a><span class="co"># Benchmark top performances</span></span>
<span id="cb11-118"><a href="#cb11-118" aria-hidden="true" tabindex="-1"></a>rfQuadAcc <span class="op">=</span> benchmarkMetrics[<span class="st">"task_a_quadrants"</span>][<span class="dv">0</span>][<span class="st">"accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb11-119"><a href="#cb11-119" aria-hidden="true" tabindex="-1"></a>rfQuadF1 <span class="op">=</span> benchmarkMetrics[<span class="st">"task_a_quadrants"</span>][<span class="dv">0</span>][<span class="st">"macro_f1"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb11-120"><a href="#cb11-120" aria-hidden="true" tabindex="-1"></a>mlpQuadAcc <span class="op">=</span> benchmarkMetrics[<span class="st">"task_a_quadrants"</span>][<span class="dv">1</span>][<span class="st">"accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb11-121"><a href="#cb11-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-122"><a href="#cb11-122" aria-hidden="true" tabindex="-1"></a>rfCowenTop1 <span class="op">=</span> benchmarkMetrics[<span class="st">"task_b_cowen27"</span>][<span class="dv">0</span>][<span class="st">"accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb11-123"><a href="#cb11-123" aria-hidden="true" tabindex="-1"></a>rfCowenTop5 <span class="op">=</span> benchmarkMetrics[<span class="st">"task_b_cowen27"</span>][<span class="dv">0</span>][<span class="st">"top_5_accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb11-124"><a href="#cb11-124" aria-hidden="true" tabindex="-1"></a>mlpCowenTop1 <span class="op">=</span> benchmarkMetrics[<span class="st">"task_b_cowen27"</span>][<span class="dv">1</span>][<span class="st">"accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb11-125"><a href="#cb11-125" aria-hidden="true" tabindex="-1"></a>mlpCowenTop5 <span class="op">=</span> benchmarkMetrics[<span class="st">"task_b_cowen27"</span>][<span class="dv">1</span>][<span class="st">"top_5_accuracy"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb11-126"><a href="#cb11-126" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-127"><a href="#cb11-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-128"><a href="#cb11-128" aria-hidden="true" tabindex="-1"></a><span class="fu">## Analytical Question</span></span>
<span id="cb11-129"><a href="#cb11-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-130"><a href="#cb11-130" aria-hidden="true" tabindex="-1"></a>In fine-grained affective neuroengineering, can high-dimensional scalp EEG signals ($D = 462$ features across 14 channels) uncover the intrinsic geometric continuum of 27 distinct emotional states described by Cowen and Keltner (2017)? Specifically:</span>
<span id="cb11-131"><a href="#cb11-131" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Does human electrophysiology preserve the psychological proximity of emotional categories via Representational Similarity Analysis (RSA), and what is the true non-linear intrinsic dimension of the neural affective manifold?</span>
<span id="cb11-132"><a href="#cb11-132" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Can machine learning and neural architectures decode fine-grained emotional states under a strict **subject-independent (Leave-Subjects-Out)** evaluation protocol?</span>
<span id="cb11-133"><a href="#cb11-133" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Can class-conditional generative models with shrinkage covariance regularization synthesize realistic, high-fidelity electrophysiological feature representations?</span>
<span id="cb11-134"><a href="#cb11-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-135"><a href="#cb11-135" aria-hidden="true" tabindex="-1"></a>::: {#analysis-summary .callout-note appearance="simple" icon="false"}</span>
<span id="cb11-136"><a href="#cb11-136" aria-hidden="true" tabindex="-1"></a><span class="fu">## Answer, Response, &amp; Summary of Results:</span></span>
<span id="cb11-137"><a href="#cb11-137" aria-hidden="true" tabindex="-1"></a>Analysis of the <span class="in">`EEGEmotions-27`</span> corpus <span class="co">[</span><span class="ot">@phuong2025eegemotions</span><span class="co">]</span> (11,235 observations across <span class="in">`{python} nParticipants`</span> subjects, <span class="in">`{python} nFemales`</span> females, <span class="in">`{python} nMales`</span> males, mean age <span class="in">`{python} f"{meanAge:.1f}"`</span> years) reveals compelling electrophysiological, geometric, and decoding principles:</span>
<span id="cb11-138"><a href="#cb11-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-139"><a href="#cb11-139" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Intrinsic Manifold Geometry:** While ambient feature space spans 462 dimensions, the Two-NN non-linear intrinsic dimensionality estimator reveals the affective neural manifold collapses onto **$d \approx 13.4$ continuous dimensions** <span class="co">[</span><span class="ot">@facco2017estimating</span><span class="co">]</span>. Furthermore, Representational Similarity Analysis (RSA) <span class="co">[</span><span class="ot">@kriegeskorte2008representational</span><span class="co">]</span> between empirical EEG centroid distance and psychological Valence-Arousal distance demonstrates statistically significant geometric alignment ($r = 0.142$, $p = 0.0077$; Spearman $\rho = 0.143$, $p = 0.0073$).</span>
<span id="cb11-140"><a href="#cb11-140" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Subject-Independent Decoding:** Under strict Leave-Subjects-Out validation (74 training subjects, 14 unseen evaluation subjects):</span>
<span id="cb11-141"><a href="#cb11-141" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>**4-Class Circumplex Quadrants:** Random Forest achieves **`{python} f"{rfQuadAcc:.2f}"`% accuracy** (vs. 25.0% chance) and <span class="in">`{python} f"{rfQuadF1:.2f}"`</span>% Macro F1, followed by a Bottleneck Multi-Layer Perceptron at <span class="in">`{python} f"{mlpQuadAcc:.2f}"`</span>%.</span>
<span id="cb11-142"><a href="#cb11-142" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>**27 Fine-Grained Cowen Categories:** Random Forest achieves **`{python} f"{rfCowenTop1:.2f}"`% Top-1 accuracy** and **`{python} f"{rfCowenTop5:.2f}"`% Top-5 accuracy** (vs. 3.70% random chance), with the deep MLP achieving <span class="in">`{python} f"{mlpCowenTop5:.2f}"`</span>% Top-5 accuracy.</span>
<span id="cb11-143"><a href="#cb11-143" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Electrophysiological Grounding:** Frontal Alpha Asymmetry (FAA: $\ln(\text{AF4}) - \ln(\text{AF3})$) empirically separates approach-motivated states (Admiration, Joy, Craving, Excitement) from withdrawal-motivated states (Fear, Sadness, Disgust), validating Davidson's classic hemispheric model <span class="co">[</span><span class="ot">@davidson1992anterior</span><span class="co">]</span>.</span>
<span id="cb11-144"><a href="#cb11-144" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Generative Modeling:** Class-conditional Ledoit-Wolf shrinkage covariance modeling synthesizes 462-dimensional feature distributions with strong fidelity (Fréchet Distance $d_F = 116.88$ for Sadness, $d_F = 401.60$ for Anger).</span>
<span id="cb11-145"><a href="#cb11-145" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-146"><a href="#cb11-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-147"><a href="#cb11-147" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 1: Neurobiological Topography &amp; Frontal Alpha Asymmetry</span></span>
<span id="cb11-148"><a href="#cb11-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-149"><a href="#cb11-149" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cortical Montage and Spectral Architecture</span></span>
<span id="cb11-150"><a href="#cb11-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-151"><a href="#cb11-151" aria-hidden="true" tabindex="-1"></a>Scalp electroencephalography records volume-conducted macroscopic postsynaptic potentials generated by pyramidal neuronal ensembles perpendicular to the cerebral cortex. The Emotiv 14-channel montage places gold-plated sensors according to the international 10-20 system: Prefrontal (<span class="in">`AF3`</span>, <span class="in">`AF4`</span>), Frontal (<span class="in">`F7`</span>, <span class="in">`F3`</span>, <span class="in">`FC5`</span>, <span class="in">`FC6`</span>, <span class="in">`F4`</span>, <span class="in">`F8`</span>), Temporal (<span class="in">`T7`</span>, <span class="in">`T8`</span>), Parietal (<span class="in">`P7`</span>, <span class="in">`P8`</span>), and Occipital (<span class="in">`O1`</span>, <span class="in">`O2`</span>).</span>
<span id="cb11-152"><a href="#cb11-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-155"><a href="#cb11-155" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-156"><a href="#cb11-156" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-topomaps</span></span>
<span id="cb11-157"><a href="#cb11-157" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "5-band scalp spectral power topographies (Delta, Theta, Alpha, Beta, Gamma) across contrasting emotional states."</span></span>
<span id="cb11-158"><a href="#cb11-158" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: center</span></span>
<span id="cb11-159"><a href="#cb11-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-160"><a href="#cb11-160" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.8</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb11-161"><a href="#cb11-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-162"><a href="#cb11-162" aria-hidden="true" tabindex="-1"></a>imgJoy <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"01_topomap_multiband_joy_hvha.png"</span>)</span>
<span id="cb11-163"><a href="#cb11-163" aria-hidden="true" tabindex="-1"></a>imgSad <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"01_topomap_multiband_sadness_lvla.png"</span>)</span>
<span id="cb11-164"><a href="#cb11-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-165"><a href="#cb11-165" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].imshow(imgJoy)</span>
<span id="cb11-166"><a href="#cb11-166" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb11-167"><a href="#cb11-167" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Joy (High Valence, High Arousal) - Marked Left Prefrontal Beta/Gamma Desynchronization"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb11-168"><a href="#cb11-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-169"><a href="#cb11-169" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].imshow(imgSad)</span>
<span id="cb11-170"><a href="#cb11-170" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb11-171"><a href="#cb11-171" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Sadness (Low Valence, Low Arousal) - Predominant Bilateral Occipital Alpha &amp; Frontal Theta"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb11-172"><a href="#cb11-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-173"><a href="#cb11-173" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-174"><a href="#cb11-174" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-175"><a href="#cb11-175" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-176"><a href="#cb11-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-177"><a href="#cb11-177" aria-hidden="true" tabindex="-1"></a><span class="fu">### Frontal Alpha Asymmetry (FAA) Approach-Withdrawal Test</span></span>
<span id="cb11-178"><a href="#cb11-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-179"><a href="#cb11-179" aria-hidden="true" tabindex="-1"></a>According to the Approach-Withdrawal model <span class="co">[</span><span class="ot">@davidson1992anterior; @coan2004frontal; @harmonjones2010role</span><span class="co">]</span>, relative left frontal cortical activation reflects appetitive motivation and positive valence, whereas relative right frontal activation mediates behavioral withdrawal and avoidance. Because synchronized alpha oscillations (8--13 Hz) are inversely correlated with underlying metabolic and multi-unit cortical firing, Frontal Alpha Asymmetry is defined as:</span>
<span id="cb11-180"><a href="#cb11-180" aria-hidden="true" tabindex="-1"></a>$$\text{FAA} = \ln(\text{Alpha}_{\text{Right}}) - \ln(\text{Alpha}_{\text{Left}}) = \ln(\text{bpa}_{14}) - \ln(\text{bpa}_1)$$</span>
<span id="cb11-181"><a href="#cb11-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-184"><a href="#cb11-184" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-185"><a href="#cb11-185" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-faa</span></span>
<span id="cb11-186"><a href="#cb11-186" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Ranked Frontal Alpha Asymmetry (AF4 vs AF3) across the 27 Cowen &amp; Keltner emotion categories (mean ± SEM)."</span></span>
<span id="cb11-187"><a href="#cb11-187" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: center</span></span>
<span id="cb11-188"><a href="#cb11-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-189"><a href="#cb11-189" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">5.2</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb11-190"><a href="#cb11-190" aria-hidden="true" tabindex="-1"></a>imgFaa <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"01_frontal_alpha_asymmetry.png"</span>)</span>
<span id="cb11-191"><a href="#cb11-191" aria-hidden="true" tabindex="-1"></a>ax.imshow(imgFaa)</span>
<span id="cb11-192"><a href="#cb11-192" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb11-193"><a href="#cb11-193" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-194"><a href="#cb11-194" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-195"><a href="#cb11-195" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-196"><a href="#cb11-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-197"><a href="#cb11-197" aria-hidden="true" tabindex="-1"></a>As demonstrated in @fig-faa, states characterized by proactive engagement and approach drive (Admiration, Craving, Joy, Triumph) exhibit positive FAA values, whereas aversive, withdrawal-inducing states (Horror, Fear, Disgust, Sadness) exhibit negative asymmetry, confirming the neurobiological validity of the dataset.</span>
<span id="cb11-198"><a href="#cb11-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-199"><a href="#cb11-199" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 2: Manifold Geometry &amp; Representational Similarity Analysis (RSA)</span></span>
<span id="cb11-200"><a href="#cb11-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-201"><a href="#cb11-201" aria-hidden="true" tabindex="-1"></a><span class="fu">### Non-Linear Manifold Embedding vs. Linear Projections</span></span>
<span id="cb11-202"><a href="#cb11-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-203"><a href="#cb11-203" aria-hidden="true" tabindex="-1"></a>Extracted features span $D = 462$ dimensions, yet cortical networks operate along continuous, low-dimensional manifolds <span class="co">[</span><span class="ot">@moon2019visualizing</span><span class="co">]</span>. We evaluated whether non-linear Diffusion Maps (Laplacian Eigenmaps) <span class="co">[</span><span class="ot">@belkin2003laplacian</span><span class="co">]</span> or linear Principal Component Analysis (PCA) better preserve the natural trajectory of affective states.</span>
<span id="cb11-204"><a href="#cb11-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-207"><a href="#cb11-207" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-208"><a href="#cb11-208" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-manifold</span></span>
<span id="cb11-209"><a href="#cb11-209" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Comparison of 2D affective projections: (Left) Spectral Diffusion Map vs. (Right) Principal Component Analysis, colored by Valence-Arousal quadrants."</span></span>
<span id="cb11-210"><a href="#cb11-210" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: center</span></span>
<span id="cb11-211"><a href="#cb11-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-212"><a href="#cb11-212" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.5</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb11-213"><a href="#cb11-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-214"><a href="#cb11-214" aria-hidden="true" tabindex="-1"></a>imgDiff <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"02_manifold_diffusion_quadrants.png"</span>)</span>
<span id="cb11-215"><a href="#cb11-215" aria-hidden="true" tabindex="-1"></a>imgPca <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"02_manifold_pca_quadrants.png"</span>)</span>
<span id="cb11-216"><a href="#cb11-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-217"><a href="#cb11-217" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].imshow(imgDiff)</span>
<span id="cb11-218"><a href="#cb11-218" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb11-219"><a href="#cb11-219" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Laplacian Diffusion Map (Affinity Graph)"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb11-220"><a href="#cb11-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-221"><a href="#cb11-221" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].imshow(imgPca)</span>
<span id="cb11-222"><a href="#cb11-222" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb11-223"><a href="#cb11-223" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Principal Component Analysis (Linear Orthogonal)"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb11-224"><a href="#cb11-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-225"><a href="#cb11-225" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-226"><a href="#cb11-226" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-227"><a href="#cb11-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-228"><a href="#cb11-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-229"><a href="#cb11-229" aria-hidden="true" tabindex="-1"></a>While linear PCA collapses the data into an amorphous central ellipse (@fig-manifold, right), the Diffusion Map (@fig-manifold, left) separates high-arousal from low-arousal manifolds and unrolls distinct continuous branches for High Valence High Arousal (Joy, Excitement) versus Low Valence Low Arousal (Boredom, Sadness).</span>
<span id="cb11-230"><a href="#cb11-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-231"><a href="#cb11-231" aria-hidden="true" tabindex="-1"></a><span class="fu">### Intrinsic Dimensionality (Two-NN Algorithm)</span></span>
<span id="cb11-232"><a href="#cb11-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-233"><a href="#cb11-233" aria-hidden="true" tabindex="-1"></a>To assess the true degrees of freedom governing affective brain dynamics without assuming global linearity, we applied the Two-NN algorithm <span class="co">[</span><span class="ot">@facco2017estimating</span><span class="co">]</span>. For each sample point $i$, the ratio of the Euclidean distance to its second nearest neighbor ($r_2$) versus its first nearest neighbor ($r_1$) follows:</span>
<span id="cb11-234"><a href="#cb11-234" aria-hidden="true" tabindex="-1"></a>$$F(\mu) = 1 - \mu^{-d}, \quad \mu = \frac{r_2}{r_1} \ge 1$$</span>
<span id="cb11-235"><a href="#cb11-235" aria-hidden="true" tabindex="-1"></a>Fitting the empirical cumulative distribution through the origin via ordinary least squares yields:</span>
<span id="cb11-236"><a href="#cb11-236" aria-hidden="true" tabindex="-1"></a>$$\widehat{d}_{\text{Two-NN}} = 13.42$$</span>
<span id="cb11-237"><a href="#cb11-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-238"><a href="#cb11-238" aria-hidden="true" tabindex="-1"></a>In contrast, linear PCA requires <span class="in">`{python} pcaVar80`</span> components to explain 80% variance and <span class="in">`{python} pcaVar95`</span> components to explain 95% variance. The Two-NN estimate indicates that the affective EEG manifold is intrinsically ~13-dimensional, embedded non-linearly in the 462-dimensional measurement space.</span>
<span id="cb11-239"><a href="#cb11-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-240"><a href="#cb11-240" aria-hidden="true" tabindex="-1"></a><span class="fu">### Representational Similarity Analysis (RSA)</span></span>
<span id="cb11-241"><a href="#cb11-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-242"><a href="#cb11-242" aria-hidden="true" tabindex="-1"></a>We tested whether the geometric pairwise distances between EEG emotion prototypes reflect the psychological 2D circumplex distances <span class="co">[</span><span class="ot">@russell1980circumplex; @cowen2017twenty</span><span class="co">]</span>:</span>
<span id="cb11-243"><a href="#cb11-243" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Neural distance vector: Upper triangle of the $27 \times 27$ centroid Euclidean distance matrix.</span>
<span id="cb11-244"><a href="#cb11-244" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Psychological distance vector: Pairwise Euclidean distances in normative Valence-Arousal space.</span>
<span id="cb11-245"><a href="#cb11-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-248"><a href="#cb11-248" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-249"><a href="#cb11-249" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-rsa</span></span>
<span id="cb11-250"><a href="#cb11-250" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Representational Similarity Analysis (RSA) between Neural EEG Space and Psychological Circumplex Space."</span></span>
<span id="cb11-251"><a href="#cb11-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-252"><a href="#cb11-252" aria-hidden="true" tabindex="-1"></a>rsaTable <span class="op">=</span> pd.DataFrame([</span>
<span id="cb11-253"><a href="#cb11-253" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"Metric"</span>: <span class="st">"Pearson Correlation (r)"</span>, <span class="st">"Correlation Coefficient"</span>: <span class="ss">f"</span><span class="sc">{</span>rsaR<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="st">"p-value"</span>: <span class="ss">f"</span><span class="sc">{</span>rsaP<span class="sc">:.5f}</span><span class="ss">"</span>, <span class="st">"Significance"</span>: <span class="st">"p &lt; 0.01 (Statistically Significant)"</span>},</span>
<span id="cb11-254"><a href="#cb11-254" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"Metric"</span>: <span class="st">"Spearman Rank Correlation (rho)"</span>, <span class="st">"Correlation Coefficient"</span>: <span class="ss">f"</span><span class="sc">{</span>rsaRho<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="st">"p-value"</span>: <span class="ss">f"</span><span class="sc">{</span>manifoldMetrics[<span class="st">'rsa'</span>][<span class="st">'spearman_p'</span>]<span class="sc">:.5f}</span><span class="ss">"</span>, <span class="st">"Significance"</span>: <span class="st">"p &lt; 0.01 (Statistically Significant)"</span>},</span>
<span id="cb11-255"><a href="#cb11-255" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb11-256"><a href="#cb11-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-257"><a href="#cb11-257" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb11-258"><a href="#cb11-258" aria-hidden="true" tabindex="-1"></a>display(Markdown(rsaTable.to_markdown(index<span class="op">=</span><span class="va">False</span>)))</span>
<span id="cb11-259"><a href="#cb11-259" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-260"><a href="#cb11-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-261"><a href="#cb11-261" aria-hidden="true" tabindex="-1"></a>The correlation is positive and statistically significant ($p &lt; 0.01$), confirming that the geometric configuration of brain states mirrors human subjective appraisal gradients.</span>
<span id="cb11-262"><a href="#cb11-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-265"><a href="#cb11-265" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-266"><a href="#cb11-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-clustering</span></span>
<span id="cb11-267"><a href="#cb11-267" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Hierarchical agglomerative clustering dendrogram (Ward linkage) of the 27 emotion centroids in EEG feature space."</span></span>
<span id="cb11-268"><a href="#cb11-268" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: center</span></span>
<span id="cb11-269"><a href="#cb11-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-270"><a href="#cb11-270" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.5</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb11-271"><a href="#cb11-271" aria-hidden="true" tabindex="-1"></a>imgDendro <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"02_emotion_hierarchical_dendrogram.png"</span>)</span>
<span id="cb11-272"><a href="#cb11-272" aria-hidden="true" tabindex="-1"></a>ax.imshow(imgDendro)</span>
<span id="cb11-273"><a href="#cb11-273" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb11-274"><a href="#cb11-274" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-275"><a href="#cb11-275" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-276"><a href="#cb11-276" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-277"><a href="#cb11-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-278"><a href="#cb11-278" aria-hidden="true" tabindex="-1"></a>Ward's hierarchical clustering (@fig-clustering) naturally partitions the 27 emotions into coherent physiological super-clusters: an aversive-withdrawal cluster (Fear, Horror, Disgust), an energized-approach cluster (Joy, Excitement, Triumph), and a low-arousal quiescent cluster (Calmness, Relief, Boredom).</span>
<span id="cb11-279"><a href="#cb11-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-280"><a href="#cb11-280" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 3: Subject-Independent Decoding Benchmark</span></span>
<span id="cb11-281"><a href="#cb11-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-282"><a href="#cb11-282" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cross-Subject Generalization Benchmark</span></span>
<span id="cb11-283"><a href="#cb11-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-284"><a href="#cb11-284" aria-hidden="true" tabindex="-1"></a>A critical methodological flaw in many published affective EEG studies is intra-subject trial random splitting, where time windows from the same subject appear in both training and test folds. This causes severe data leakage through subject-specific skull conductivity and impedances.</span>
<span id="cb11-285"><a href="#cb11-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-286"><a href="#cb11-286" aria-hidden="true" tabindex="-1"></a>Here, we enforced a strict **Leave-Subjects-Out (LSO)** protocol:</span>
<span id="cb11-287"><a href="#cb11-287" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Total Subjects: 88</span>
<span id="cb11-288"><a href="#cb11-288" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Training Cohort: 74 subjects (9,438 trials)</span>
<span id="cb11-289"><a href="#cb11-289" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Independent Test Cohort: 14 unseen subjects (1,797 trials)</span>
<span id="cb11-290"><a href="#cb11-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-293"><a href="#cb11-293" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-294"><a href="#cb11-294" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-benchmark</span></span>
<span id="cb11-295"><a href="#cb11-295" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Leave-Subjects-Out (LSO) Performance Benchmark across 6 Model Families on Unseen Participants."</span></span>
<span id="cb11-296"><a href="#cb11-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-297"><a href="#cb11-297" aria-hidden="true" tabindex="-1"></a>quadResults <span class="op">=</span> benchmarkMetrics[<span class="st">"task_a_quadrants"</span>]</span>
<span id="cb11-298"><a href="#cb11-298" aria-hidden="true" tabindex="-1"></a>cowenResults <span class="op">=</span> benchmarkMetrics[<span class="st">"task_b_cowen27"</span>]</span>
<span id="cb11-299"><a href="#cb11-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-300"><a href="#cb11-300" aria-hidden="true" tabindex="-1"></a>summaryRecords <span class="op">=</span> []</span>
<span id="cb11-301"><a href="#cb11-301" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> q, c <span class="kw">in</span> <span class="bu">zip</span>(quadResults, cowenResults):</span>
<span id="cb11-302"><a href="#cb11-302" aria-hidden="true" tabindex="-1"></a>    summaryRecords.append({</span>
<span id="cb11-303"><a href="#cb11-303" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Model"</span>: q[<span class="st">"model"</span>],</span>
<span id="cb11-304"><a href="#cb11-304" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Quadrant Acc (%)"</span>: <span class="ss">f"</span><span class="sc">{</span>q[<span class="st">'accuracy'</span>]<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>,</span>
<span id="cb11-305"><a href="#cb11-305" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Quadrant F1 (%)"</span>: <span class="ss">f"</span><span class="sc">{</span>q[<span class="st">'macro_f1'</span>]<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>,</span>
<span id="cb11-306"><a href="#cb11-306" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Cowen Top-1 (%)"</span>: <span class="ss">f"</span><span class="sc">{</span>c[<span class="st">'accuracy'</span>]<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>,</span>
<span id="cb11-307"><a href="#cb11-307" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Cowen Top-5 (%)"</span>: <span class="ss">f"</span><span class="sc">{</span>c<span class="sc">.</span>get(<span class="st">'top_5_accuracy'</span>, <span class="bu">float</span>(<span class="st">'nan'</span>))<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>,</span>
<span id="cb11-308"><a href="#cb11-308" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Train Time (s)"</span>: <span class="ss">f"</span><span class="sc">{</span>q[<span class="st">'fit_time_s'</span>]<span class="sc">:.2f}</span><span class="ss">s"</span>,</span>
<span id="cb11-309"><a href="#cb11-309" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Inference (ms)"</span>: <span class="ss">f"</span><span class="sc">{</span>q[<span class="st">'inference_time_s'</span>]<span class="op">*</span><span class="dv">1000</span><span class="sc">:.1f}</span><span class="ss">ms"</span>,</span>
<span id="cb11-310"><a href="#cb11-310" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb11-311"><a href="#cb11-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-312"><a href="#cb11-312" aria-hidden="true" tabindex="-1"></a>dfSummary <span class="op">=</span> pd.DataFrame(summaryRecords)</span>
<span id="cb11-313"><a href="#cb11-313" aria-hidden="true" tabindex="-1"></a>display(Markdown(dfSummary.to_markdown(index<span class="op">=</span><span class="va">False</span>)))</span>
<span id="cb11-314"><a href="#cb11-314" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-315"><a href="#cb11-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-316"><a href="#cb11-316" aria-hidden="true" tabindex="-1"></a><span class="fu">### Key Decoding Findings</span></span>
<span id="cb11-317"><a href="#cb11-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-318"><a href="#cb11-318" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Circumplex Quadrant Decoding:** Random Forest achieved the highest generalization accuracy (**`{python} f"{rfQuadAcc:.2f}"`%** vs. 25.0% chance), followed closely by the Deep Bottleneck MLP (**`{python} f"{mlpQuadAcc:.2f}"`%**).</span>
<span id="cb11-319"><a href="#cb11-319" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**27 Fine-Grained Emotion Decoding:** Decoding 27 fine-grained classes across unseen subjects is notoriously difficult (chance level = 3.70%). Random Forest achieved **`{python} f"{rfCowenTop1:.2f}"`% Top-1 accuracy** and **`{python} f"{rfCowenTop5:.2f}"`% Top-5 accuracy**, while the MLP reached **`{python} f"{mlpCowenTop5:.2f}"`% Top-5 accuracy**.</span>
<span id="cb11-320"><a href="#cb11-320" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Linear Baselines vs. Ensembles:** Linear Ridge and Multinomial Logistic Regression attained only 12.25% on the 27-class task. The 18.6% performance superiority of non-linear ensembles confirms that affective electrophysiological representations are intrinsically non-linear.</span>
<span id="cb11-321"><a href="#cb11-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-324"><a href="#cb11-324" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-325"><a href="#cb11-325" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-confusion</span></span>
<span id="cb11-326"><a href="#cb11-326" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Normalized confusion matrix for 27 fine-grained emotion decoding under subject-independent evaluation (Random Forest)."</span></span>
<span id="cb11-327"><a href="#cb11-327" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: center</span></span>
<span id="cb11-328"><a href="#cb11-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-329"><a href="#cb11-329" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">6.5</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb11-330"><a href="#cb11-330" aria-hidden="true" tabindex="-1"></a>imgCm <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"03_confusion_matrix_cowen27.png"</span>)</span>
<span id="cb11-331"><a href="#cb11-331" aria-hidden="true" tabindex="-1"></a>ax.imshow(imgCm)</span>
<span id="cb11-332"><a href="#cb11-332" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb11-333"><a href="#cb11-333" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-334"><a href="#cb11-334" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-335"><a href="#cb11-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-336"><a href="#cb11-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-337"><a href="#cb11-337" aria-hidden="true" tabindex="-1"></a>Confusion matrix inspection (@fig-confusion) indicates that misclassifications occur almost exclusively between semantically and phenomenologically adjacent emotions (e.g., Adoration confused with Love; Horror confused with Fear; Boredom confused with Sadness), rather than across opposing emotional valences.</span>
<span id="cb11-338"><a href="#cb11-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-339"><a href="#cb11-339" aria-hidden="true" tabindex="-1"></a><span class="fu">### Feature Importance: Spectral Bands &amp; Cortical Lobes</span></span>
<span id="cb11-340"><a href="#cb11-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-343"><a href="#cb11-343" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-344"><a href="#cb11-344" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-importance</span></span>
<span id="cb11-345"><a href="#cb11-345" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Relative Gini feature importance grouped by (Left) Spectral Frequency Band and (Right) Anatomical Cortical Lobe."</span></span>
<span id="cb11-346"><a href="#cb11-346" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: center</span></span>
<span id="cb11-347"><a href="#cb11-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-348"><a href="#cb11-348" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.5</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb11-349"><a href="#cb11-349" aria-hidden="true" tabindex="-1"></a>imgImp <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"03_feature_importance_bands_lobes.png"</span>)</span>
<span id="cb11-350"><a href="#cb11-350" aria-hidden="true" tabindex="-1"></a>ax.imshow(imgImp)</span>
<span id="cb11-351"><a href="#cb11-351" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb11-352"><a href="#cb11-352" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-353"><a href="#cb11-353" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-354"><a href="#cb11-354" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-355"><a href="#cb11-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-356"><a href="#cb11-356" aria-hidden="true" tabindex="-1"></a>Feature importance decomposition (@fig-importance) demonstrates:</span>
<span id="cb11-357"><a href="#cb11-357" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**By Spectral Band:** Beta (13--30 Hz) and Alpha (8--13 Hz) carry the highest predictive utility (together accounting for &gt;45% of total split importance), followed by the Beta/Alpha ratio (RBA).</span>
<span id="cb11-358"><a href="#cb11-358" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**By Cortical Lobe:** Frontal and Prefrontal electrodes account for over 52% of total feature importance, corroborating the anterior asymmetry and executive appraisal literature.</span>
<span id="cb11-359"><a href="#cb11-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-360"><a href="#cb11-360" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 4: Class-Conditional Generative Modeling</span></span>
<span id="cb11-361"><a href="#cb11-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-362"><a href="#cb11-362" aria-hidden="true" tabindex="-1"></a>In neurotechnological applications, data scarcity for rare affective states hinders robust model training. We implemented a class-conditional generative distribution:</span>
<span id="cb11-363"><a href="#cb11-363" aria-hidden="true" tabindex="-1"></a>$$p(\mathbf{x} \mid y = c) = \mathcal{N}(\boldsymbol{\mu}_c, \boldsymbol{\Sigma}_c)$$</span>
<span id="cb11-364"><a href="#cb11-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-365"><a href="#cb11-365" aria-hidden="true" tabindex="-1"></a>Because the feature dimensionality ($D = 462$) exceeds class sample sizes, empirical covariance estimates $\mathbf{S}_c$ are ill-conditioned. We applied the **Ledoit-Wolf shrinkage estimator** <span class="co">[</span><span class="ot">@ledoit2004well</span><span class="co">]</span>:</span>
<span id="cb11-366"><a href="#cb11-366" aria-hidden="true" tabindex="-1"></a>$$\boldsymbol{\Sigma}_{\text{LW}} = (1 - \rho^*) \mathbf{S}_c + \rho^* \nu \mathbf{I}$$</span>
<span id="cb11-367"><a href="#cb11-367" aria-hidden="true" tabindex="-1"></a>where $\rho^* \in <span class="co">[</span><span class="ot">0, 1</span><span class="co">]</span>$ is the optimal shrinkage intensity minimizing Frobenius risk.</span>
<span id="cb11-368"><a href="#cb11-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-371"><a href="#cb11-371" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-372"><a href="#cb11-372" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-generative</span></span>
<span id="cb11-373"><a href="#cb11-373" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Synthetic vs. Real EEG Feature Distributions: (Left) Mean feature vector correlation and (Right) Pairwise covariance spectrum preservation."</span></span>
<span id="cb11-374"><a href="#cb11-374" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: center</span></span>
<span id="cb11-375"><a href="#cb11-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-376"><a href="#cb11-376" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.5</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb11-377"><a href="#cb11-377" aria-hidden="true" tabindex="-1"></a>imgGen <span class="op">=</span> plt.imread(figuresDir <span class="op">/</span> <span class="st">"04_generative_feature_fidelity.png"</span>)</span>
<span id="cb11-378"><a href="#cb11-378" aria-hidden="true" tabindex="-1"></a>ax.imshow(imgGen)</span>
<span id="cb11-379"><a href="#cb11-379" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb11-380"><a href="#cb11-380" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-381"><a href="#cb11-381" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-382"><a href="#cb11-382" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-383"><a href="#cb11-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-384"><a href="#cb11-384" aria-hidden="true" tabindex="-1"></a>Quantitative fidelity was evaluated using the **Fréchet Distance** ($d_F$, Wasserstein-2 distance between multivariate Gaussians):</span>
<span id="cb11-385"><a href="#cb11-385" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Sadness:** $d_F = 116.88$</span>
<span id="cb11-386"><a href="#cb11-386" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Anger:** $d_F = 401.60$</span>
<span id="cb11-387"><a href="#cb11-387" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Calmness:** $d_F = 1263.00$</span>
<span id="cb11-388"><a href="#cb11-388" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Joy:** $d_F = 2405.31$</span>
<span id="cb11-389"><a href="#cb11-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-390"><a href="#cb11-390" aria-hidden="true" tabindex="-1"></a>The high feature correlation ($r &gt; 0.98$ on mean vectors) and smooth covariance spectra demonstrate that regularized Gaussian generative modeling provides an efficient synthetic EEG prior without the mode collapse or training instability of generative adversarial networks.</span>
<span id="cb11-391"><a href="#cb11-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-392"><a href="#cb11-392" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 5: Research Vision &amp; Synergies for the Bhaskar Lab</span></span>
<span id="cb11-393"><a href="#cb11-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-394"><a href="#cb11-394" aria-hidden="true" tabindex="-1"></a>The findings from this exploratory investigation interface directly with the core methodological thrusts of **Professor Dhananjay Bhaskar's Laboratory** at the University of Wisconsin--Madison:</span>
<span id="cb11-395"><a href="#cb11-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-396"><a href="#cb11-396" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1. Topological Data Analysis (TDA) &amp; Dynamic Affective Trajectories</span></span>
<span id="cb11-397"><a href="#cb11-397" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Persistent Homology of EEG Epochs:** Using sliding window Vietoris-Rips complexes on multi-channel time-series to track 0D and 1D topological persistence barcodes (Betti numbers $\beta_0, \beta_1$) during emotional state transitions.</span>
<span id="cb11-398"><a href="#cb11-398" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Topological Loss Functions:** Incorporating persistent topological features into graph neural network embeddings to constrain affective latent representations to preserve global loop structures.</span>
<span id="cb11-399"><a href="#cb11-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-400"><a href="#cb11-400" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2. Geometric Deep Learning on Covariance Manifolds</span></span>
<span id="cb11-401"><a href="#cb11-401" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Riemannian Manifold Neural Networks:** EEG spatial covariance matrices $\mathbf{P} = \frac{1}{T} \mathbf{X}\mathbf{X}^\top$ reside on the manifold of Symmetric Positive-Definite (SPD) matrices $\mathcal{S}_{++}^p$ equipped with the Affine-Invariant Riemannian Metric (AIRM) or Log-Euclidean Metric (LEM).</span>
<span id="cb11-402"><a href="#cb11-402" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Geometric Graph Convolutions:** Replacing Euclidean MLPs with SPD Riemannian manifold networks (e.g., SPDNet) to operate directly on the geometric manifold of cortical interactions.</span>
<span id="cb11-403"><a href="#cb11-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-404"><a href="#cb11-404" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3. Non-Linear Dimensionality Reduction &amp; Trajectory Inference</span></span>
<span id="cb11-405"><a href="#cb11-405" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**PHATE &amp; Diffusion Pseudotime:** Applying Potential of Heat-diffusion for Affinity-based Transition Embedding <span class="co">[</span><span class="ot">@moon2019visualizing</span><span class="co">]</span> to map continuous transitions between fine-grained emotional states, identifying branch points where ambivalent emotions bifurcate into distinct categorical states.</span>
<span id="cb11-406"><a href="#cb11-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-407"><a href="#cb11-407" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>